<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>whiley</string>
	</array>
	<key>name</key>
	<string>Whiley</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>//[^/]*</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.whiley</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.whiley</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(false|true|null)\b</string>
			<key>name</key>
			<string>constant.language.whiley</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(function|method|property|type|variant)\b</string>
			<key>name</key>
			<string>entity.name.function.whiley</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.whiley</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.whiley</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.whiley</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.whiley</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(import)\s*([a-zA-Z0-9:]+)\s*(with)\s*([a-zA-Z_0-9]+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.whiley</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.whiley</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.whiley</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.whiley</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(import)\s*([a-zA-Z0-9_]+)\s*(from)\s*([a-zA-Z0-9:]+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.whiley</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.whiley</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(import)\s*([a-zA-Z0-9:]+)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(assert|assume|break|case|continue|debug|default|do|else|ensures|fail|for|if|requires|return|skip|switch|where|while)\b</string>
			<key>name</key>
			<string>keyword.control.whiley</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(all|in|is|new|no|old|some)\b</string>
			<key>name</key>
			<string>keyword.operator.word.whiley</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(bool|byte|export|final|int|native|private|protected|public|unsafe|void)\b</string>
			<key>name</key>
			<string>keyword.other.whiley</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(-)?[0-9.]+\b</string>
			<key>name</key>
			<string>constant.numeric.whiley</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(&amp;&amp;|\|\||!|==&gt;|&lt;==&gt;)</string>
			<key>name</key>
			<string>keyword.operator.logical.whiley</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(&lt;=|&lt;|&gt;=|&gt;|==|!=|\+|-|\*|/)</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.whiley</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^package\b</string>
			<key>name</key>
			<string>entity.name.class.whiley</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>punctuation.definition.string.whiley</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped-char</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[_A-Z][_A-Z0-9]+\b</string>
			<key>name</key>
			<string>variable.constant.whiley</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[_a-zA-Z][_a-zA-Z0-9]*_t\b</string>
			<key>name</key>
			<string>entity.name.type.whiley</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[_a-zA-Z][_a-zA-Z0-9]*\b</string>
			<key>name</key>
			<string>variable.whiley</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>escaped-char</key>
		<dict>
			<key>match</key>
			<string>\\.</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.whiley</string>
	<key>uuid</key>
	<string>5ee71b5b-00f0-4a98-904e-fccb7a06569f</string>
</dict>
</plist>
